######################################################################
# Automatically generated by qmake (2.01a) ?? 12? 11 15:35:07 2017
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += flowchartsymbolpicker.h
SOURCES += flowchartsymbolpicker.cpp main.cpp
