######################################################################
# Automatically generated by qmake (2.01a) ?? 12? 13 13:48:59 2017
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += currencymodel.h
SOURCES += currencymodel.cpp main.cpp
