######################################################################
# Automatically generated by qmake (2.01a) ?? 12? 12 16:27:41 2017
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += directoryviewer.h
SOURCES += directoryviewer.cpp main.cpp
