######################################################################
# Automatically generated by qmake (2.01a) ?? 12? 11 17:23:56 2017
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += coordinatesetter.h
SOURCES += coordinatesetter.cpp main.cpp
