######################################################################
# Automatically generated by qmake (2.01a) ?? 12? 14 10:25:49 2017
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += booleanmodel.h booleanparser.h booleanwindow.h node.h
SOURCES += booleanmodel.cpp \
           booleanparser.cpp \
           booleanwindow.cpp \
           main.cpp \
           node.cpp
