######################################################################
# Automatically generated by qmake (2.01a) ?? 12? 12 15:15:34 2017
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += teamleaderdialog.h
SOURCES += main.cpp teamleaderdialog.cpp
