######################################################################
# Automatically generated by qmake (2.01a) ?? 12? 13 10:05:15 2017
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += colornamesdialog.h
SOURCES += colornamesdialog.cpp main.cpp
