######################################################################
# Automatically generated by qmake (2.01a) ?? 12? 13 14:51:03 2017
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += citymodel.h
SOURCES += citymodel.cpp main.cpp
