######################################################################
# Automatically generated by qmake (2.01a) ?? 10? 27 10:48:50 2017
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += main.cpp
