######################################################################
# Automatically generated by qmake (2.01a) ?? 12? 15 11:26:33 2017
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += teamleadersdialog.h
SOURCES += main.cpp teamleadersdialog.cpp
