######################################################################
# Automatically generated by qmake (2.01a) ?? 12? 14 16:59:01 2017
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += trackdelegate.h trackeditor.h
SOURCES += main.cpp trackdelegate.cpp trackeditor.cpp
